export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const BUY_BURGER_SUCCESS = 'BUY_BURGER_SUCCESS';
export const BUY_BURGER_FAIL = 'BUY_BURGER_FAIL';
export const BUY_BURGER_START = 'BUY_BURGER_START';
export const BUY_INIT = 'BUY_INIT';